### ISSUE TITLE
Static and dynamic friction across various physics engines

### ISSUE THREAD

**Issue by robertlong** [eoineoineoin/glTF_Physics#13]
During our OMI glTF extensions call we noticed MSFT_physics has both `dynamicFriction` and `staticFriction` which is present in the USD spec as well as in PhysX. Unreal's Chaos, Godot, and Rapier.js do not split friction into dynamic and static friction. This could be fine, but how would we be expected to set a single friction property when we have different dynamic/static friction values?

**Comment by eoineoineoin** [comment]
My gut feeling would be that such an engine would just use the `dynamicFriction` value, but that's a pretty arbitrary decision on my part - I don't have a solid mathematical justification for choosing either (or a mix.)
