### ISSUE TITLE
Inertia tensor is a symmtric matrix, should we reduce redundant information?

### ISSUE THREAD

**Issue by aaronfranke** [eoineoineoin/glTF_Physics#14]
https://en.wikipedia.org/wiki/Moment_of_inertia

I see that a 3x3 matrix inertia tensor is guaranteed to be a symmetric matrix, so an inertia tensor 3x3 matrix only has 6 unique numbers. I am wondering if it should really be a 9-element array as currently in this repo, or if it should be a 6-element array, with the principle axis values and coupling values? Or maybe either a 3-element or 6-element array, to make the coupling values optional? Or maybe two 3-element arrays, one for the principle axis values and one for the coupling values?

I asked ChatGPT for help: https://gist.github.com/aaronfranke/754f55c3d181e18154c9dccf801f9050

If we desire a 3x3 matrix, I would define the symmetric property explicitly in the spec like this:

> ### Inertia Tensor
> 
> The `"inertiaTensor"` property is an array of 9 numbers that defines the inertia tensor 3x3 matrix of the body in kilogram meter squared (kg⋅m²). The inertia tensor matrix is a symmetric matrix.

EDIT: OMI has decided that the 3x3 matrix representation is good. We should still explicitly document its properties.

EDIT 2: We have discovered that Rapier physics uses only principle axis inertia, like Godot, but it allows the principle axes to be different from the body's axes. We should account for this and provide conversions. https://www.rapier.rs/javascript3d/classes/RigidBodyDesc.html#angularInertiaLocalFrame

**Comment by eoineoineoin** [comment]
I surveyed a bunch of tools and the prevailing representation in the UI (at least) is definitely rotation+vector inertia (like your Rapier physics example), which is probably the easiest combination for users to edit intuitively. So, thoughts on making the schema specify:

Optional rotation quaternion.
Optional principal axis.

**Comment by aaronfranke** [comment]
I am not an expert on inertia, but I am not against that. Regardless we must provide formulas to convert between the different representations so that implementations can implement it correctly.

**Comment by aaronfranke** [comment]
For representing infinity in the inertia tensor while infinity is not a valid value in JSON, I found this in Unity: https://docs.unity3d.com/ScriptReference/Rigidbody-inertiaTensor.html

> Zero is not a valid inertia tensor component. Therefore, the physics system interprets zeros as infinite values instead. So, for example, a body with (0, 1, 1) inertia tensor is impossible to rotate around X.

So I guess we could use 0 for this. The only tricky part here is that in both Unity and Godot, the default value of (0, 0, 0) means that the physics engine should calculate the inertia automatically, so you could not do infinity on all three axes to create an un-rotateable body (but I don't think this is a big deal honestly).

**Comment by eoineoineoin** [comment]
I'd actually be more inclined to store the inverse mass. That preserves the $\mathbb{R} \mapsto \mathbb{R}$  behaviour without needing to special-case some values (and physics engines typically store the inverse mass/inertia anyway) - that "infininity on all three axes" issue is just how the UI presents the configuration, so it's easy to fix up.

**Comment by aaronfranke** [comment]
OMI has added the inertia tensor 3x3 matrix to our spec, we agree it's good: https://github.com/omigroup/gltf-extensions/pull/145

But this issue is still useful for discussing the finer details, like infinity values.
