### ISSUE TITLE
Errors with Joint schemas

### ISSUE THREAD

**Issue by aaronfranke** [eoineoineoin/glTF_Physics#21]
https://github.com/eoineoineoin/glTF_Physics/tree/master/MSFT_rigid_bodies/schema

The repo currently has these files:

* `glTF.MSFT_rigid_bodies.joint.schema.json`
* `glTF.MSFT_rigid_bodies.joint_limit.schema.json`
* `glTF.MSFT_rigid_bodies.joint_limit_set.schema.json`
* `node.MSFT_rigid_bodies.joint.schema.json`

Problem 1: `glTF.MSFT_rigid_bodies.joint.schema.json` and `glTF.MSFT_rigid_bodies.joint_limit_set.schema.json` are duplicates of each other. They both contain `"properties": { "limits": { "type": "array"`. However, each file has slightly different contents. I would guess that the name `joint_limit_set` is preferred, but I'm not sure.

Problem 2: Neither of the duplicate schemas is referenced anywhere. The `glTF.MSFT_rigid_bodies.schema.json` file references `glTF.MSFT_rigid_bodies.joint_limit.schema.json` but based on [this example](https://github.com/eoineoineoin/glTF_Physics/blob/master/samples/WaterWheel/WaterWheel.gltf#L20) I think it was supposed to reference the `joint_limit_set` schema.

**Comment by aaronfranke** [comment]
@eoineoineoin Your joint schemas are still not correct. The document schema has this in it:

```json
        "physicsJointLimits": {
            "type": "array",
            "description": "An array of physics joint limit descriptions.",
            "items": {
                "type": "object",
                "$ref": "glTF.KHR_rigid_bodies.joint_limit.schema.json"
            },
            "minItems": 1
        },
```

However, based on the examples and the other schemas, this is supposed to refer to `joint`, not `joint_limit`.

Also, some other questions:

* Why is the `physics` prefix in the name? It's already inside of `KHR_rigid_bodies`, it's already physics.
* Why does a node's `"joint": {}` have `jointLimits`? I think it should just be "limits", because it's already inside of the joint. We don't put `"physicsMass"` or `"bodyMass"` inside of `"motion"`, just `"mass"`.
* Why was the word "limit" chosen instead of "constraint"? The latter would be a more descriptive term, more specific, more searchable, and avoids duplication with the constraint's parts ("a constraint may have a min/max limit" is better than saying "a limit may have a min/max limit").

**Comment by eoineoineoin** [comment]
> However, based on the examples and the other schemas, this is supposed to refer to `joint`, not `joint_limit`.

Yes, seems to be; will get that fixed, thanks.
 
>     * Why is the `physics` prefix in the name? It's already inside of `KHR_rigid_bodies`, it's already physics.

/Mainly because the "joint" is already heavily overloaded in the context of animations. This helps disambiguate and minimize confusion. As the spec goes through ratification, I expect that field names will be closely scrutinized, but I don't think this is a big deal for now.

>     * Why does a node's `"joint": {}` have `jointLimits`? I think it should just be "limits", because it's already inside of the joint. We don't put `"physicsMass"` or `"bodyMass"` inside of `"motion"`, just `"mass"`.

Yes, but will want to add some additional fields to the joint object, so will probably rename this field to something different.
 
>     * Why was the word "limit" chosen instead of "constraint"? The latter would be a more descriptive term, more specific, more searchable, and avoids duplication with the constraint's parts ("a constraint may have a min/max limit" is better than saying "a limit may have a min/max limit").

The word "limit" is what every physics engine (including, Bullet, Chaos, Havok, Godot, Jolt, ODE, Newton, PhysX) I've looked at uses to describe this functionality. If you want to avoid using the word "limit" twice in such a sentence, you might reword it like "a constraint may have a min/max bound"

**Comment by aaronfranke** [comment]
> The word "limit" is what every physics engine (including, Bullet, Chaos, Havok, Godot, Jolt, ODE, Newton, PhysX) I've looked at uses to describe this functionality.

What? Are you sure? I don't think they do.

Godot uses constraint: https://docs.godotengine.org/en/stable/classes/class_joint3d.html "apply a constraint".
Jolt uses constraint: https://jrouwe.github.io/JoltPhysics/ "Bodies can be connected to each other using constraints"
O3DE with PhysX uses "constrain": https://docs.o3de.org/docs/user-guide/interactivity/physics/nvidia-physx/joint-intro/
Panda3D with Bullet uses constraint: https://docs.panda3d.org/1.10/python/programming/physics/bullet/constraints
Unity uses "limit" to describe the min/max of a joint constraint: https://docs.unity3d.com/Manual/class-ConfigurableJoint.html
Unreal uses constraint: https://docs.unrealengine.com/5.3/en-US/physics-constraint-component-user-guide-in-unreal-engine/

**Comment by eoineoineoin** [comment]
> > Mainly because the "joint" is already heavily overloaded in the context of animations.
> 
> Do you mean skeletons?

Nope; original was correct. However, "skeleton" is also a term used in the context of animations, if you're unfamiliar.

> > The word "limit" is what every physics engine (including, Bullet, Chaos, Havok, Godot, Jolt, ODE, Newton, PhysX) I've looked at uses to describe this functionality.
> 
> What? Are you sure? I don't think they do.
> 
> Godot uses constraint: https://docs.godotengine.org/en/stable/classes/class_joint3d.html "apply a constraint". Jolt uses constraint: https://jrouwe.github.io/JoltPhysics/ "Bodies can be connected to each other using constraints" O3DE with PhysX uses "constrain": https://docs.o3de.org/docs/user-guide/interactivity/physics/nvidia-physx/joint-intro/ Panda3D with Bullet uses constraint: https://docs.panda3d.org/1.10/python/programming/physics/bullet/constraints Unity uses "limit" to describe the min/max of a joint constraint: https://docs.unity3d.com/Manual/class-ConfigurableJoint.html Unreal uses constraint: https://docs.unrealengine.com/5.3/en-US/physics-constraint-component-user-guide-in-unreal-engine/

Yes, they do:

Godot uses "limit": https://docs.godotengine.org/en/stable/classes/class_generic6dofjoint3d.html#class-generic6dofjoint3d-property-angular-limit-x-lower-angle
Jolt uses "limit": https://jrouwe.github.io/JoltPhysics/class_six_d_o_f_constraint.html#a19166b2e56147da794b2651896007294
PhysX uses "limit": https://docs.nvidia.com/gameworks/content/gameworkslibrary/physx/guide/Manual/Joints.html#limits
Bullet uses "limit": https://pybullet.org/Bullet/BulletFull/classBullet_1_1btGeneric6DofConstraintData.html#ada91ce5a07c0d070191706b2195f6cf3
Chaos uses "limit": https://docs.unrealengine.com/4.26/en-US/InteractiveExperiences/Physics/Constraints/ConstraintsReference/#linearlimits
