### ISSUE TITLE
Sleeping Entities

### ISSUE THREAD

**Issue by Shinmera** [eoineoineoin/glTF_Physics#24]
When constructing complex scenes like a wall made out of bricks it can be useful for authors to be able to designate certain entities as being asleep at the start of the scene, to avoid simulation instability causing issues.

Would an asleep boolean property be an acceptable addition?

**Comment by eoineoineoin** [comment]
I'd really like to avoid this. It doesn't map to a real physical property, and, in terms of simulation, "sleeping" essentially a hack - particularly when used for stability reasons; in engines which do support sleeping, bodies can wake for a variety of different (non-obvious) reasons and anything which causes those objects to wake would break the apparent stability. Realistically, to preserve stability in such a case, an engine would need additional data anyway, like impulse history or Jacobian ordering info.

An individual application could, of course decide to add bodies as sleeping, but I don't think it should be configured in the file, as it could lead to inconsistencies; having sleeping body with a non-zero velocity doesn't make sense; similarly, an asset with a sleeping body could be instanced with a transform which results in unintuitively floating/penetrating bodies.

**Comment by eoineoineoin** [comment]
Closing as "not planned" - trying to add this kind of property is too leaky and complex, IMO.
