### ISSUE TITLE
Invalid JSON

### ISSUE THREAD

**Issue by YclepticStudios** [eoineoineoin/glTF_Physics#27]
The following line contains a JSON formatting error. The square bracket should be replaced with a curly brace.

https://github.com/eoineoineoin/glTF_Physics/blob/master/extensions/2.0/Khronos/KHR_physics_rigid_bodies/schema/glTF.KHR_physics_rigid_bodies.joint_drive.schema.json#L71

**Comment by eoineoineoin** [comment]
Thanks
