### ISSUE TITLE
Inconsistently named file

### ISSUE THREAD

**Issue by YclepticStudios** [eoineoineoin/glTF_Physics#28]
The following file name is missing the "schema" keyword.
Most likely this should match the other files and be `node.KHR_physics_rigid_bodies.collider.schema.json`.

https://github.com/eoineoineoin/glTF_Physics/blob/master/extensions/2.0/Khronos/KHR_physics_rigid_bodies/schema/node.KHR_physics_rigid_bodies.collider.json

**Comment by eoineoineoin** [comment]
Thanks!
