### ISSUE TITLE
Rename "mesh" collider type to "trimesh" to avoid ambiguity 

### ISSUE THREAD

**Issue by robertlong** [eoineoineoin/glTF_Physics#3]
The glTF spec already uses the `mesh` property to refer to mesh indices, so it might be better to rename the collider type to `trimesh` to avoid confusion.

Ex:

```json
"collider": {
  "mesh": {
    "mesh": 0
  }
}
```

becomes

```json
"collider": {
  "trimesh": {
    "mesh": 0
  }
}
```

**Comment by eoineoineoin** [comment]
Yes, 100% agree. Thanks.
