### ISSUE TITLE
Example assets for joint drives and joint drive axis schema mistake

### ISSUE THREAD

**Issue by aaronfranke** [eoineoineoin/glTF_Physics#34]
It seems that there are no glTF files in the samples folder using joint drives, can we get an example?

Also, I noticed that the axis property is on a range of 0 to 3:

```json
        "axis": {
            "type": "integer",
            "minimum": 0,
            "maximum": 3,
            "description": "The index of the axis which this drive applies forces on."
        },
```

I believe this is a mistake. Is it supposed to be 0 to 2, representing 0 for X, 1 for Y, and 2 for Z?

**Comment by aaronfranke** [comment]
On the topic of joint drives, I'm confused about how `positionTarget` and `velocityTarget` work. If a joint is currently at position 5 and has a position target of 5 and a velocity target of 1, does it try to move past 5 at a velocity of 1, or does it only try to obtain a velocity of 1 when below 5 and will stop once it reaches 5? If it's at 10 with the same targets, does it try to move down to 5 at a velocity of 1? So basically, are both of these targets active at once? What would happen if it was desired for a drive to move or spin forever, should the position target be infinity?

**Comment by eoineoineoin** [comment]
> position 5 and has a position target of 5 and a velocity target of 1, does it try to move past 5 at a velocity of 1, or does it only try to obtain a velocity of 1 when below 5 and will stop once it reaches 5? If it's at 10 with the same targets, does it try to move down to 5 at a velocity of 1? So basically, are both of these targets active at once?

Yes, both targets are active at the same time, and the behaviour is determined by the equation documented in the README.md:

$stiffness * (positionTarget - positionCurrent) + damping * (velocityTarget - velocityCurrent)$

> What would happen if it was desired for a drive to move or spin forever, should the position target be infinity?

Likely, you want to set the velocity target to the desired value.

**Comment by aaronfranke** [comment]
> Likely, you want to set the velocity target to the desired value.

Does position target have a default value? Do I need to set the position target to infinity to keep it going forever? Or is it treated as "don't use a position target" if not defined? If so, this should be stated.
